name: ci

on:
  push:
    branches:
      - main

jobs:
  laravel-tests:
    name: Api Rest Library
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testing
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pgsql, pdo_pgsql, mbstring, bcmath, xml, dom, fileinfo,
          coverage: none

      - name: Start postgresql service
        run: sudo systemctl start postgresql.service

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader --no-suggest

      - name: Prepare the application
        run: |
          cp .env.ci .env
          php artisan key:generate

      - name: Clear Config
        run: |
          php artisan config:clear
          php artisan config:cache

      - name: Migrate the database
        run: php artisan migrate --force

      - name: Run tests
        run: php artisan test --testsuite=Feature

